// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:b3cfabad-98ca-43f9-8605-d788f296dafb',
    'aws_cognito_region': 'us-east-1',
    'aws_mobile_analytics_app_id': 'dc937fc4bafe449cbf786fb896056de1',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'c8edd3f4-e3d9-4348-86f7-ef614ba4de3c',
    'aws_project_name': 'MoveAwareness',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'moveawareness-mobilehub-160519728',
}

export default awsmobile;
