// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:f7f9feac-bf1b-42ed-aeea-1b49d15c1813',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'moveawareness-hosting-mobilehub-1755283049',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd2efpej999v52r.cloudfront.net',
    'aws_mobile_analytics_app_id': 'e027bf5a135c49649d313f3227d51fb7',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'be433c20-a652-4c93-b861-0d4411fb4348',
    'aws_project_name': 'moveawareness',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'moveawareness-mobilehub-1755283049',
}

export default awsmobile;
